services:
  - type: web
    name: youtube-downloader
    runtime: docker
    repo: https://github.com/AZLabsAI/youtube-downloader
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
